baseURL = 'https://decapcms.org'
disableFastRender = true
languageCode = 'en-us'
defaultContentLanguage = 'en'
title = 'Decap CMS | Open-Source Content Management System'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "catppuccin-frappe"
    tabWidth = 2
    guessSyntax = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[params]
  description = 'Open source content management for your Git workflow'

[menu]
  [[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 10
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 20
  [[menu.main]]
    name = "Community"
    url = "/community/"
    weight = 30
  [[menu.main]]
    name = "Pro Help"
    url = "/services/"
    weight = 40
