# Main navigation menu
main:
  - name: Resources
    identifier: resources
    weight: 10
  - name: Documentation
    url: /docs/intro
    parent: resources
    weight: 11
  - name: Blog
    url: /blog/
    parent: resources
    weight: 12
  - name: What's New
    url: https://github.com/decaporg/decap-cms/releases
    parent: resources
    weight: 13
  - name: About
    url: /about/
    parent: resources
    weight: 14
  - name: Support
    identifier: support
    weight: 20
  - name: Services
    url: /services/
    parent: support
    weight: 21
  - name: Community
    url: /community/
    parent: support
    weight: 22
  - name: Features
    identifier: features
    weight: 30
  - name: For Developers
    url: /features/developer
    parent: features
    weight: 31
  - name: For Editors
    url: /features/editor
    parent: features
    weight: 32
  - name: Decap Turbo
    url: /turbo/
    weight: 40

# Docs navigation menu
docs:
  - name: Intro to Decap CMS
    identifier: Intro
    weight: 10
  - name: Add To Your Site
    identifier: Add
    weight: 20
  - name: Account Settings
    identifier: Accounts
    weight: 30
  - name: Configuring your Site
    identifier: Configuration
    weight: 40
  - name: Media
    identifier: Media
    weight: 50
  - name: Workflow
    identifier: Workflow
    weight: 60
  - name: Collections
    identifier: Collections
    weight: 70
  - name: Fields
    identifier: Fields
    weight: 80
  - name: Platform Guides
    identifier: Guides
    weight: 90
  - name: Customizing Decap CMS
    identifier: Customization
    weight: 100
  - name: Community
    identifier: Contributing
    weight: 110
